import User from './User';
import CharacterApartment from './CharacterApartment';
import CharacterBusiness from './CharacterBusiness';
import CharacterHouse from './CharacterHouse';
import CharacterInventory from './CharacterInventory';
import CharacterSkill from './CharacterSkill';
import CharacterVehicle from './CharacterVehicle';
import Contact from './Contact';
import Faction from './Faction';
import FactionMember from './FactionMember';
import Message from './Message';
import Entity from '../Entity';

export default class Character extends Entity<Character> {
    public firstName: string;
    public lastName: string;
    public cash: number;
    public bank: number;
    public dead: boolean;
    public phoneNumber: string;
    public health: number;
    public armor: number;
    public arrestTime: number;
    public dimension: number;
    public lastPosition: string;
    public id: number;
    public fkUserId: number;
    public fkUser: User;
    public characterApartments: CharacterApartment[];
    public characterBusinesses: CharacterBusiness[];
    public characterHouses: CharacterHouse[];
    public characterInventory: CharacterInventory;
    public characterSkills: CharacterSkill[];
    public characterVehicles: CharacterVehicle[];
    public contacts: Contact[];
    public contacts2: Contact[];
    public faction: Faction;
    public factionMember: FactionMember;
    public messages: Message[];
    public messages2: Message[];
}
